### ISSUE TITLE
Tag v1.0-3 doesn't exists.

### ISSUE THREAD

**Issue by seregatte** [ophal/seawolf#4]
I tried install this library via luarocks, but I had this message:

```
Installing http://luarocks.org/repositories/rocks/seawolf-1.0-3.rockspec...
Using http://luarocks.org/repositories/rocks/seawolf-1.0-3.rockspec... switching to 'build' mode
Cloning into 'seawolf'...
warning: Could not find remote branch v1.0-3 to clone.
fatal: Remote branch v1.0-3 not found in upstream origin
```
I think it happened because the tag or branch doesn't exists.
```
$ git tag
v0.6-alpha1
v0.7-alpha1
v0.8-1
v0.8-2
v1.0-1
v1.0-2

$ git branch
* master
```

**Comment by develCuy** [comment]
What a surprise João!

I forgot to push the tag, sorry about that.

Btw, just pushed a new release 1.0-4. You will need to update your config.lua (usually installed at /etc/luarocks) see: wy.si/17

Let me know how it goes.

**Comment by seregatte** [comment]
Thanks!

Worked very well!
